- hosts: localhost
  become: true
  tasks:

    - name: Criando arquivo Index.html
      file:
        path: /var/www/html/index.html
        state: touch
        mode: u=rw,g=r,o=r
        owner: apache
        group: apache

    - name: Criando arquivo error404.html
      file:
        path: /var/www/html/error404.html
        state: touch
        mode: u=rw,g=r,o=r
        owner: apache
        group: apache

    - name: Redirecionando index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Fazendo hardening no apache com Ansible"
        create: yes
    
    - name: Criando arquivo 404 customizado
      lineinfile:
        path: /var/www/html/error404.html
        line: "Ops, o que você procurou não existe, cheque a URL"
        create: yes

    - name: Redirecionando error 404
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: ErrorDocument 404 /error404.html
        create: yes
  
    - name: Instalando o mod_security
      yum:
        name: mod_security
        state: present
    
    - name: Suprindo versão do apache - parte 1 de 2
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: ServerTokens Full
        create: yes

    - name: Suprindo versão do apache - parte 2 de 2
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: ServerSignature Off
        create: yes

    - name: Mudando o cabeçalho/header Server
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: SecServerSignature "Microsoft-IIS/6.0"
        create: yes

    - name: Reiniciando o serviço do apache/httpd
      service:
        name: httpd
        state: restarted
        enabled: yes