- hosts: localhost
  become: true
  tasks:

    - name: Instalação do apache
      yum:
        name: httpd
        state: present

    - name: Iniciando e habiltiando o serviço
      service:
        name: httpd
        state: started
        enabled: yes
    
    - name: Liberando regra no firewall
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Reiniciar o firewall
      service: 
        name: firewalld 
        state: restarted